# Generated by Django 2.1.5 on 2019-08-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20190829_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='year',
            field=models.CharField(max_length=120),
        ),
    ]
